### ISSUE TITLE
No data from Plugwise Stretch

### ISSUE THREAD

**Issue by Eilandgast** [athombv/com.plugwise#3]
I have solarpanels (2 separate strings of 9 panels each) connected to a Growatt 4400TL inverter. This inverter communicates wireless with a Plugwise Stretch. No problem to get all the data with the Plugwise Desktop (PC) and with the App on my Android phone and iPad also without a problem.
Now I try to to get readings via Homey. The Plugwise App installs normal in Homey. Also Homey finds (when given the pass code of Stretch) the two strings of panels and asks whats connected (I choose "other"). In Insights the two strings of panels are visual and one can mark Aangezet, Energie, Stroommeter . But theres no Graph produced. Only a dot which says (with mouse over) Energie: 0 Watt or Stroommeter: 0kWh.
I placed some pictures at https://forum.athom.com/discussion/2704/flow-for-solar-panels-and-plugwise-stretch

**Comment by RobinBol** [comment]
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2547
