### ISSUE TITLE
Add some functions

### ISSUE THREAD

**Issue by Slofware** [athombv/com.plugwise#6]
Is it possible on the Anna app to see in a flow it the CV is burning so I can switch some pumps.

**Comment by RobinBol** [comment]
Thank you for reporting your issue. Currently the App repository issue trackers are not being monitored, all (App related) issues should be reported at https://github.com/athombv/homey/issues. Alternatively, use the 'Report an issue' button on the App page in the Homey Apps store to create an issue at the correct location. This issue will be closed now, our apologies for the inconvenience.
--
